.PHONY: clean All

All:
	@echo "----------Building project:[ BatalhaNaval - Debug ]----------"
	@cd "BatalhaNaval" && "$(MAKE)" -f  "BatalhaNaval.mk"
clean:
	@echo "----------Cleaning project:[ BatalhaNaval - Debug ]----------"
	@cd "BatalhaNaval" && "$(MAKE)" -f  "BatalhaNaval.mk" clean
